name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:

  create-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: gh release create ${{ github.ref_name }} --draft --title "${{ github.ref_name }}"
    env:
      GH_TOKEN: ${{ github.token }}
  publish-exes:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-latest
            rid: osx-arm64
          - os: macos-13
            rid: osx-x64

    runs-on: ${{ matrix.os }}
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Publish executables (Windows)
        if: matrix.os == 'windows-latest'
        run: ./publish.ps1 ${{env.VERSION}} ${{ secrets.STORAGE_APIKEY }} ${{ matrix.rid }}
        shell: pwsh
        env:
          VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ github.token }}

      - name: Publish executables (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: ./publish.sh ${{env.VERSION}} ${{ secrets.STORAGE_APIKEY }} ${{ matrix.rid }}
        shell: bash
        env:
          VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ github.token }}

