name: Publish Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish script
        run: ./publish.sh ${{env.VERSION}} ${{ secrets.STORAGE_APIKEY }} ${{ secrets.NUGET_APIKEY }}
        env:
          VERSION: ${{ env.VERSION }}
